pipeline{
    agent any
    stages{
        stage('Build Frontend'){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/benbuselola/tingesoProyecto1']])
                dir("frontBanco"){
                    bat "npm install"
                    bat "npm run build"
                }

            }
        }
        stage('Deploy'){
            steps{
                dir("frontBanco"){
                    script{
                        bat "docker context use default"
                        withDockerRegistry(credentialsId: 'docker-credentials'){
                            bat "docker build -t bbustamante13/frontend-imagen ."
                            bat "docker push bbustamante13/frontend-imagen"
                        }
                    }
                }
            }
        }
    }
}