version: "3.8"
services:
  nginx-backend:
    image: nginx
    container_name: gestion-banco-nginx-backend-container
    restart: always
    ports:
      - "8090:8090"
    volumes:
      - ./backend.conf:/etc/nginx/nginx.conf
    networks:
      - gestion-banco-backend-network
    depends_on:
      - spring1
      - spring2
      - spring3
  nginx-frontend:
    image: nginx
    container_name: gestion-banco-nginx-frontend-container
    restart: always
    ports:
      - "8070:80"
    volumes:
      - ./frontend.conf:/etc/nginx/nginx.conf
    networks:
      - gestion-banco-frontend-network
    depends_on:
      - react1
      - react2
      - react3
  postgres:
    container_name: gestion-banco-postgres-container
    image: postgres
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - gestion-banco-postgres-volume:/var/lib/postgresql/data
    networks:
      - gestion-banco-backend-network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 13101310
    ports:
      - "5435:5432"
  spring1:
    container_name: gestion-banco-backend-container-1
    image: bbustamante13/spring-image
    ports:
      - "8091:8090"
    environment:
      DB_HOST: gestion-banco-postgres-container
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 13101310
    networks:
      - gestion-banco-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  spring2:
    container_name: gestion-banco-backend-container-2
    image: bbustamante13/spring-image
    ports:
      - "8092:8090"
    environment:
      DB_HOST: gestion-banco-postgres-container
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 13101310
    networks:
      - gestion-banco-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  spring3:
    container_name: gestion-banco-backend-container-3
    image: bbustamante13/spring-image
    ports:
      - "8093:8090"
    environment:
      DB_HOST: gestion-banco-postgres-container
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: 13101310
    networks:
      - gestion-banco-backend-network
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres
  react1:
    container_name: gestion-banco-frontend-container-1
    image: bbustamante13/frontend-sinst
    ports:
      - "3001:3000"
    networks:
      - gestion-banco-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react2:
    container_name: gestion-banco-frontend-container-2
    image: bbustamante13/frontend-sinst
    ports:
      - "3002:3000"
    networks:
      - gestion-banco-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
  react3:
    container_name: gestion-banco-frontend-container-3
    image: bbustamante13/frontend-sinst
    ports:
      - "3003:3000"
    networks:
      - gestion-banco-frontend-network
    deploy:
      restart_policy:
        condition: on-failure
volumes:
  gestion-banco-postgres-volume:
networks:
  gestion-banco-backend-network:
  gestion-banco-frontend-network:            